import os
import django
from django.utils.text import slugify

# Set up Django environment
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'quiz_project.settings')
django.setup()

from quiz.models import Category, Quiz, Question, Answer

def create_question(quiz, text, choices, correct_index):
    question, created = Question.objects.get_or_create(quiz=quiz, text=text)
    if created:
        for i, choice_text in enumerate(choices):
            Answer.objects.create(
                question=question,
                text=choice_text,
                is_correct=(i == correct_index)
            )

def get_category(name, slug_str=None):
    if not slug_str:
        slug_str = slugify(name)
    # Use update_or_create to ensure slugs are updated if they were wrong
    category, _ = Category.objects.update_or_create(
        name=name,
        defaults={'slug': slug_str}
    )
    return category

def get_quiz(title, description, category, slug_str=None):
    if not slug_str:
        slug_str = slugify(title)
    quiz, _ = Quiz.objects.update_or_create(
        title=title,
        category=category,
        defaults={'description': description, 'slug': slug_str}
    )
    return quiz

def seed_data():
    print("Seeding data...")
    
    # --- Categories ---
    tech = get_category("Technology")
    GK = get_category("General Knowledge")
    science = get_category("Science")
    history = get_category("History")
    sports = get_category("Sports")
    geography = get_category("Geography")
    literature = get_category("Literature")
    movies = get_category("Movies")
    flat_cat = get_category("FLAT", "flat-theory")
    cd_cat = get_category("Compiler Design", "compiler-design")
    os_cat = get_category("Operating Systems", "operating-systems")
    dbms_cat = get_category("DBMS", "dbms-theory")
    c_cat = get_category("C Programming", "c-programming")
    cpp_cat = get_category("C++ Programming", "cpp-programming")
    java_cat = get_category("Java Programming", "java-programming")
    html_cat = get_category("HTML", "html-basics")
    css_cat = get_category("CSS", "css-styling")
    js_cat = get_category("JavaScript", "javascript-programming")
    design_cat = get_category("Software Design", "software-design")
    cloud_cat = get_category("Cloud Computing", "cloud-computing")

    # --- Quizzes ---
    # Python
    py_quiz = get_quiz("Python Basics", "Test your fundamental knowledge of Python programming.", tech)
    create_question(py_quiz, "Who created Python?", ["Guido van Rossum", "Elon Musk", "Bill Gates", "Mark Zuckerberg"], 0)
    create_question(py_quiz, "Which of the following is an immutable type?", ["List", "Dictionary", "Tuple", "Set"], 2)
    create_question(py_quiz, "How do you start a comment in Python?", ["//", "/*", "#", "--"], 2)
    create_question(py_quiz, "What is the correct way to create a function in Python?", ["def my_func():", "function my_func()", "create my_func()", "sub my_func()"], 0)
    create_question(py_quiz, "Which of these is used to handle exceptions?", ["try-except", "catch", "throw", "error"], 0)
    create_question(py_quiz, "What is the output of len([1, 2, 3])?", ["3", "2", "4", "1"], 0)
    create_question(py_quiz, "Which keyword is used to create a class in Python?", ["class", "struct", "impl", "define"], 0)
    create_question(py_quiz, "How do you import a module in Python?", ["import module", "require module", "include module", "using module"], 0)
    create_question(py_quiz, "What is the result of 3 * 3 in Python?", ["9", "6", "27", "12"], 0)
    create_question(py_quiz, "Which method adds an element to the end of a list?", ["append()", "add()", "push()", "insert()"], 0)
    create_question(py_quiz, "What does PEP 8 stand for?", ["Python Enhancement Proposal", "Python Easy Program", "Program Enhancement Plan", "Personal Enhancement Plan"], 0)
    create_question(py_quiz, "Which of these is a Python web framework?", ["Django", "React", "Angular", "Vue"], 0)
    create_question(py_quiz, "What is the result of 10 // 3?", ["3", "3.33", "4", "3.0"], 0)
    create_question(py_quiz, "Which built-in function is used to output text?", ["print()", "echo()", "write()", "log()"], 0)
    create_question(py_quiz, "How do you check the type of an object?", ["type()", "typeof()", "kind()", "class()"], 0)

    # Space
    space_quiz = get_quiz("Space Exploration", "Journey through the stars with this space-themed quiz.", GK)
    create_question(space_quiz, "Which planet is known as the Red Planet?", ["Mars", "Venus", "Jupiter", "Saturn"], 0)
    create_question(space_quiz, "What is the largest planet in our solar system?", ["Earth", "Jupiter", "Neptune", "Uranus"], 1)
    create_question(space_quiz, "Who was the first person to walk on the moon?", ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "Michael Collins"], 0)
    create_question(space_quiz, "What is the name of the closest galaxy to the Milky Way?", ["Andromeda", "Magellanic", "Sombrero", "Whirlpool"], 0)
    create_question(space_quiz, "What is the largest moon of Saturn?", ["Titan", "Ganymede", "Europa", "Io"], 0)
    create_question(space_quiz, "Which planet is famous for its prominent ring system?", ["Saturn", "Jupiter", "Uranus", "Neptune"], 0)
    create_question(space_quiz, "What was the name of the first artificial satellite?", ["Sputnik 1", "Explorer 1", "Vanguard 1", "Vostok 1"], 0)
    create_question(space_quiz, "What is a 'shooting star' actually called?", ["Meteor", "Comet", "Asteroid", "Pulsar"], 0)
    create_question(space_quiz, "Which planet in our solar system is the hottest?", ["Venus", "Mercury", "Mars", "Jupiter"], 0)
    create_question(space_quiz, "What force keeps the planets in orbit around the Sun?", ["Gravity", "Magnetism", "Centrifugal Force", "Friction"], 0)
    create_question(space_quiz, "What is the name of our galaxy?", ["Milky Way", "Andromeda", "Triangulum", "Sombrero"], 0)
    create_question(space_quiz, "Which is the smallest planet in our solar system?", ["Mercury", "Mars", "Pluto", "Earth"], 0)
    create_question(space_quiz, "How many moons does Mars have?", ["2", "1", "0", "4"], 0)
    create_question(space_quiz, "What is the name of the NASA rover that landed on Mars in 2021?", ["Perseverance", "Curiosity", "Opportunity", "Spirit"], 0)
    create_question(space_quiz, "Which planet is known as the 'Morning Star'?", ["Venus", "Mercury", "Jupiter", "Saturn"], 0)

    # Biology
    bio_quiz = get_quiz("Biology Basics", "Explore the world of living organisms.", science)
    create_question(bio_quiz, "What is the powerhouse of the cell?", ["Mitochondria", "Nucleus", "Ribosome", "Vacuole"], 0)
    create_question(bio_quiz, "Which gas do plants absorb from the atmosphere?", ["Carbon Dioxide", "Oxygen", "Nitrogen", "Hydrogen"], 0)
    create_question(bio_quiz, "How many bones are in the adult human body?", ["206", "180", "250", "212"], 0)
    create_question(bio_quiz, "What is the study of plants called?", ["Botany", "Zoology", "Mycology", "Ecology"], 0)
    create_question(bio_quiz, "Which organ is responsible for pumping blood throughout the body?", ["Heart", "Lungs", "Brain", "Liver"], 0)
    create_question(bio_quiz, "What is the genetic material in most organisms?", ["DNA", "RNA", "Protein", "ATP"], 0)
    create_question(bio_quiz, "What do you call an animal that eats only plants?", ["Herbivore", "Carnivore", "Omnivore", "Detritivore"], 0)
    create_question(bio_quiz, "What is the largest organ of the human body?", ["Skin", "Liver", "Large Intestine", "Brain"], 0)
    create_question(bio_quiz, "Which vitamin is produced by the human skin when exposed to sunlight?", ["Vitamin D", "Vitamin C", "Vitamin A", "Vitamin B12"], 0)
    create_question(bio_quiz, "What is the process by which a caterpillar transforms into a butterfly?", ["Metamorphosis", "Evolution", "Photosynthesis", "Meiosis"], 0)
    create_question(bio_quiz, "What is the primary function of white blood cells?", ["Fighting infection", "Carrying oxygen", "Clotting blood", "Storing fat"], 0)
    create_question(bio_quiz, "What is the structural unit of all living organisms?", ["Cell", "Tissue", "Organ", "System"], 0)
    create_question(bio_quiz, "Which part of the brain controls balance and coordination?", ["Cerebellum", "Cerebrum", "Medulla", "Thalamus"], 0)
    create_question(bio_quiz, "What type of organism is a mushroom?", ["Fungus", "Plant", "Bacterium", "Protist"], 0)
    create_question(bio_quiz, "Which pigment gives plants their green color?", ["Chlorophyll", "Carotene", "Melanin", "Hemoglobin"], 0)

    # History
    hist_quiz = get_quiz("World War II", "Test your knowledge of the second World War.", history)
    create_question(hist_quiz, "In which year did WWII end?", ["1945", "1939", "1941", "1950"], 0)
    create_question(hist_quiz, "Who was the Prime Minister of the UK during most of WWII?", ["Winston Churchill", "Neville Chamberlain", "Clement Attlee", "Margaret Thatcher"], 0)
    create_question(hist_quiz, "What was the code name for the Allied invasion of Normandy?", ["Operation Overlord", "Operation Barbarossa", "Operation Torch", "Operation Market Garden"], 0)
    create_question(hist_quiz, "Which country was invaded to start WWII?", ["Poland", "France", "Austria", "Russia"], 0)
    create_question(hist_quiz, "What was the name of the German air force during WWII?", ["Luftwaffe", "RAF", "Stuka", "Wehrmacht"], 0)
    create_question(hist_quiz, "Which US president made the decision to use atomic bombs against Japan?", ["Harry S. Truman", "Franklin D. Roosevelt", "Dwight D. Eisenhower", "John F. Kennedy"], 0)
    create_question(hist_quiz, "What was the site of the surprise attack on the US Pacific Fleet in 1941?", ["Pearl Harbor", "Midway", "Iwo Jima", "Guadalcanal"], 0)
    create_question(hist_quiz, "Which battle was the turning point on the Eastern Front?", ["Battle of Stalingrad", "Battle of Kursk", "Battle of Berlin", "Battle of Britain"], 0)
    create_question(hist_quiz, "Who was the leader of the Soviet Union during WWII?", ["Joseph Stalin", "Vladimir Lenin", "Leon Trotsky", "Nikita Khrushchev"], 0)
    create_question(hist_quiz, "What treaty ended WWI but contributed to the start of WWII?", ["Treaty of Versailles", "Treaty of Paris", "Treaty of Utrecht", "Treaty of Tordesillas"], 0)
    create_question(hist_quiz, "Who were the primary 'Axis' powers?", ["Germany, Italy, Japan", "UK, USA, USSR", "Germany, Russia, Japan", "France, UK, USA"], 0)
    create_question(hist_quiz, "Which major battle was fought in the Pacific in 1942?", ["Battle of Midway", "Battle of the Bulge", "Battle of Alamein", "Battle of Jutland"], 0)
    create_question(hist_quiz, "What was the name of the project that developed the atomic bomb?", ["Manhattan Project", "Project X", "Enigma Project", "Apollo Project"], 0)
    create_question(hist_quiz, "Which country signed a non-aggression pact with Germany in 1939?", ["Soviet Union", "USA", "France", "UK"], 0)
    create_question(hist_quiz, "In which Japanese city was the first atomic bomb dropped?", ["Hiroshima", "Nagasaki", "Tokyo", "Kyoto"], 0)

    # Sports
    sports_quiz = get_quiz("Football (Soccer)", "A quiz for football fans around the world.", sports)
    create_question(sports_quiz, "Which country has won the most FIFA World Cups?", ["Brazil", "Germany", "Italy", "Argentina"], 0)
    create_question(sports_quiz, "How many players are on the field for one team in a standard match?", ["11", "10", "12", "15"], 0)
    create_question(sports_quiz, "Who holds the record for the most goals in a single calendar year?", ["Lionel Messi", "Cristiano Ronaldo", "Pele", "Gerd Muller"], 0)
    create_question(sports_quiz, "In which country is the 'Maracanã' stadium located?", ["Brazil", "Argentina", "Uruguay", "Spain"], 0)
    create_question(sports_quiz, "What is the maximum number of substitutions allowed in a standard competitive match (post-2022)?", ["5", "3", "4", "6"], 0)
    create_question(sports_quiz, "Which player has won the most Ballon d'Or awards?", ["Lionel Messi", "Cristiano Ronaldo", "Michel Platini", "Johan Cruyff"], 0)
    create_question(sports_quiz, "Which English club has won the most Champions League titles?", ["Liverpool", "Manchester United", "Chelsea", "Arsenal"], 0)
    create_question(sports_quiz, "Which manager is famously known as 'The Special One'?", ["Jose Mourinho", "Pep Guardiola", "Sir Alex Ferguson", "Arsene Wenger"], 0)
    create_question(sports_quiz, "What is the duration of a standard football match (excluding injury time)?", ["90 minutes", "80 minutes", "100 minutes", "45 minutes"], 0)
    create_question(sports_quiz, "Which country hosted the first-ever FIFA World Cup in 1930?", ["Uruguay", "Italy", "France", "Brazil"], 0)
    create_question(sports_quiz, "Which player is known as 'O Rei' (The King)?", ["Pele", "Maradona", "Messi", "Zidane"], 0)
    create_question(sports_quiz, "Which team won the FIFA World Cup in 2022?", ["Argentina", "France", "Croatia", "Morocco"], 0)
    create_question(sports_quiz, "What is the term for a player scoring three goals in a single game?", ["Hat-trick", "Brace", "Turkey", "Grand Slam"], 0)
    create_question(sports_quiz, "Which stadium is known as 'The Theatre of Dreams'?", ["Old Trafford", "Anfield", "Wembley", "Etihad"], 0)
    create_question(sports_quiz, "Which country originated the modern game of football?", ["England", "China", "Scotland", "Italy"], 0)

    # Geography
    geo_quiz = get_quiz("World Capitals", "Test your knowledge of world capitals.", geography)
    create_question(geo_quiz, "What is the capital of France?", ["Paris", "Lyon", "Marseille", "Nice"], 0)
    create_question(geo_quiz, "What is the capital of Japan?", ["Tokyo", "Osaka", "Kyoto", "Nagoya"], 0)
    create_question(geo_quiz, "What is the capital of Australia?", ["Canberra", "Sydney", "Melbourne", "Perth"], 0)
    create_question(geo_quiz, "What is the capital of Canada?", ["Ottawa", "Toronto", "Vancouver", "Montreal"], 0)
    create_question(geo_quiz, "What is the capital of Brazil?", ["Brasilia", "Rio de Janeiro", "Sao Paulo", "Salvador"], 0)
    create_question(geo_quiz, "What is the capital of Italy?", ["Rome", "Milan", "Naples", "Florence"], 0)
    create_question(geo_quiz, "What is the capital of Egypt?", ["Cairo", "Alexandria", "Giza", "Luxor"], 0)
    create_question(geo_quiz, "What is the capital of India?", ["New Delhi", "Mumbai", "Kolkata", "Chennai"], 0)
    create_question(geo_quiz, "What is the capital of the United Kingdom?", ["London", "Manchester", "Birmingham", "Edinburgh"], 0)
    create_question(geo_quiz, "What is the capital of South Africa?", ["Pretoria", "Johannesburg", "Durban", "Soweto"], 0)
    create_question(geo_quiz, "What is the capital of Germany?", ["Berlin", "Munich", "Frankfurt", "Hamburg"], 0)
    create_question(geo_quiz, "What is the capital of Russia?", ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg"], 0)
    create_question(geo_quiz, "What is the capital of Mexico?", ["Mexico City", "Cancun", "Guadalajara", "Monterrey"], 0)
    create_question(geo_quiz, "What is the capital of South Korea?", ["Seoul", "Busan", "Incheon", "Daegu"], 0)
    create_question(geo_quiz, "What is the capital of Spain?", ["Madrid", "Barcelona", "Valencia", "Seville"], 0)

    # Literature
    lit_quiz = get_quiz("Classic Literature", "Journey through the greatest works of literature.", literature)
    create_question(lit_quiz, "Who wrote 'Romeo and Juliet'?", ["William Shakespeare", "Christopher Marlowe", "John Milton", "Dante Alighieri"], 0)
    create_question(lit_quiz, "Who wrote 'Pride and Prejudice'?", ["Jane Austen", "Charlotte Brontë", "George Eliot", "Mary Shelley"], 0)
    create_question(lit_quiz, "What is the name of the whale in Herman Melville's 'Moby Dick'?", ["Moby Dick", "Bluey", "Orca", "Nemo"], 0)
    create_question(lit_quiz, "Who wrote the dystopian novel '1984'?", ["George Orwell", "Aldous Huxley", "Ray Bradbury", "H.G. Wells"], 0)
    create_question(lit_quiz, "Who wrote 'The Great Gatsby'?", ["F. Scott Fitzgerald", "Ernest Hemingway", "William Faulkner", "John Steinbeck"], 0)
    create_question(lit_quiz, "Who wrote 'War and Peace'?", ["Leo Tolstoy", "Fyodor Dostoevsky", "Anton Chekhov", "Ivan Turgenev"], 0)
    create_question(lit_quiz, "Who wrote 'Don Quixote'?", ["Miguel de Cervantes", "Gabriel Garcia Marquez", "Jorge Luis Borges", "Pablo Neruda"], 0)
    create_question(lit_quiz, "Which ancient Greek poet is credited with 'The Odyssey'?", ["Homer", "Sophocles", "Euripides", "Hesiod"], 0)
    create_question(lit_quiz, "Who wrote the novel 'Jane Eyre'?", ["Charlotte Brontë", "Emily Brontë", "Anne Brontë", "George Sand"], 0)
    create_question(lit_quiz, "Who wrote 'Les Misérables'?", ["Victor Hugo", "Alexandre Dumas", "Gustave Flaubert", "Honore de Balzac"], 0)
    create_question(lit_quiz, "Who wrote 'The Grapes of Wrath'?", ["John Steinbeck", "William Faulkner", "Ernest Hemingway", "Harper Lee"], 0)
    create_question(lit_quiz, "Who wrote 'Ulysses'?", ["James Joyce", "Virginia Woolf", "Samuel Beckett", "T.S. Eliot"], 0)
    create_question(lit_quiz, "Who wrote 'Crime and Punishment'?", ["Fyodor Dostoevsky", "Leo Tolstoy", "Anton Chekhov", "Vladimir Nabokov"], 0)
    create_question(lit_quiz, "Who wrote 'The Catcher in the Rye'?", ["J.D. Salinger", "Jack Kerouac", "Truman Capote", "Allen Ginsberg"], 0)
    create_question(lit_quiz, "Who wrote 'The Picture of Dorian Gray'?", ["Oscar Wilde", "Bram Stoker", "Robert Louis Stevenson", "H.G. Wells"], 0)

    # Movies
    movie_quiz = get_quiz("Cinema History", "Test your knowledge of movies and directors.", movies)
    create_question(movie_quiz, "Who directed 'Jurassic Park'?", ["Steven Spielberg", "George Lucas", "James Cameron", "Martin Scorsese"], 0)
    create_question(movie_quiz, "What was the first feature-length animated movie?", ["Snow White and the Seven Dwarfs", "Pinocchio", "Bambi", "Fantasia"], 0)
    create_question(movie_quiz, "In 'The Godfather', who played the role of Vito Corleone?", ["Marlon Brando", "Al Pacino", "Robert De Niro", "Joe Pesci"], 0)
    create_question(movie_quiz, "Who directed 'Pulp Fiction'?", ["Quentin Tarantino", "Guy Ritchie", "David Fincher", "Christopher Nolan"], 0)
    create_question(movie_quiz, "Which movie features the line 'Here's looking at you, kid'?", ["Casablanca", "Gone with the Wind", "Citizen Kane", "The Wizard of Oz"], 0)
    create_question(movie_quiz, "What is the highest-grossing film of all time (unadjusted for inflation)?", ["Avatar", "Avengers: Endgame", "Titanic", "Star Wars: The Force Awakens"], 0)
    create_question(movie_quiz, "Who played the character Jack Sparrow in Pirates of the Caribbean?", ["Johnny Depp", "Orlando Bloom", "Brad Pitt", "Tom Cruise"], 0)
    create_question(movie_quiz, "Which movie won the first-ever Academy Award for Best Picture?", ["Wings", "The Broadway Melody", "Cimarron", "Grand Hotel"], 0)
    create_question(movie_quiz, "Who directed the sci-fi epic 'Interstellar'?", ["Christopher Nolan", "Denis Villeneuve", "Ridley Scott", "James Gray"], 0)
    create_question(movie_quiz, "Which actor played the Joker in 'The Dark Knight'?", ["Heath Ledger", "Jack Nicholson", "Jared Leto", "Joaquin Phoenix"], 0)
    create_question(movie_quiz, "Who directed 'The Shawshank Redemption'?", ["Frank Darabont", "Steven Spielberg", "Martin Scorsese", "Francis Ford Coppola"], 0)
    create_question(movie_quiz, "Which movie features a character named 'Forrest Gump'?", ["Forrest Gump", "Cast Away", "Saving Private Ryan", "Apollo 13"], 0)
    create_question(movie_quiz, "Who directed the 'Lord of the Rings' trilogy?", ["Peter Jackson", "Ridley Scott", "David Yates", "Sam Raimi"], 0)
    create_question(movie_quiz, "What is the name of the kingdom in 'Frozen'?", ["Arendelle", "Genovia", "Florin", "DunBroch"], 0)
    create_question(movie_quiz, "Which film is about a young boy who can see dead people?", ["The Sixth Sense", "The Others", "The Orphanage", "The Conjuring"], 0)

    # --- FLAT ---
    flat_quiz = get_quiz("Automata Theory", "Test your knowledge on DFA, NFA, and Grammars.", flat_cat)
    create_question(flat_quiz, "What is the most powerful machine in automata theory?", ["Turing Machine", "DFA", "PDA", "NFA"], 0)
    create_question(flat_quiz, "Which of the following is equivalent to a Regular Grammar?", ["Finite Automata", "Pushdown Automata", "Linear Bounded Automata", "Turing Machine"], 0)
    create_question(flat_quiz, "The set of all strings ending with '00' is recognized by which machine?", ["DFA", "PDA", "Turing Machine", "None"], 0)
    create_question(flat_quiz, "Pumping Lemma is generally used for proving a language is NOT:", ["Regular", "Context-free", "Recursive", "Decidable"], 0)
    create_question(flat_quiz, "A Pushdown Automata is used to recognize which languages?", ["Context-Free", "Regular", "Context-Sensitive", "Recursive"], 0)
    create_question(flat_quiz, "Which automata uses a stack?", ["PDA", "DFA", "NFA", "Turing Machine"], 0)
    create_question(flat_quiz, "The language {a^n b^n | n >= 0} is:", ["Context-Free", "Regular", "Context-Sensitive", "Recursive"], 0)
    create_question(flat_quiz, "What does NFA stand for?", ["Non-deterministic Finite Automata", "Navigation Finite Automata", "Non-finite Automata", "Node Finite Automata"], 0)
    create_question(flat_quiz, "Every Regular Language is also Context-Free?", ["True", "False", "Only for finite sets", "None"], 0)
    create_question(flat_quiz, "The intersection of two regular languages is:", ["Regular", "Context-Free", "Non-Regular", "Recursive"], 0)
    create_question(flat_quiz, "Which grammar is used by compilers for syntax analysis?", ["Context-Free Grammar", "Regular Grammar", "Unrestricted Grammar", "Context-Sensitive Grammar"], 0)
    create_question(flat_quiz, "A Turing machine has infinite memory in the form of:", ["Tape", "Stack", "Register", "Queue"], 0)
    create_question(flat_quiz, "Halting problem is:", ["Undecidable", "Decidable", "Regular", "Context-Free"], 0)
    create_question(flat_quiz, "The complement of a regular language is:", ["Regular", "Non-Regular", "Context-Free", "Context-Sensitive"], 0)
    create_question(flat_quiz, "DFA and NFA have equal expressive power?", ["True", "False", "Only for alphabets", "None"], 0)

    # --- CD ---
    cd_quiz = get_quiz("Compiler Design", "Master the phases of a compiler.", cd_cat)
    create_question(cd_quiz, "Which phase of the compiler produces an intermediate representation?", ["Intermediate Code Generation", "Lexical Analysis", "Syntax Analysis", "Code Optimization"], 0)
    create_question(cd_quiz, "What tool is used for Lexical Analysis?", ["LEX", "YACC", "ANTLR", "Bison"], 0)
    create_question(cd_quiz, "A Symbol Table is used for storing:", ["Variable names and types", "Source code", "Binary code", "Error logs"], 0)
    create_question(cd_quiz, "Syntax analysis is also known as:", ["Parsing", "Scanning", "Optimization", "Linking"], 0)
    create_question(cd_quiz, "Which parser is a top-down parser?", ["Recursive Descent", "LR", "LALR", "SLR"], 0)
    create_question(cd_quiz, "Left-factoring is required to eliminate:", ["Non-determinism", "Left-recursion", "Ambiguity", "Redundancy"], 0)
    create_question(cd_quiz, "What is the output of Lexical Analysis?", ["Tokens", "Parse Tree", "Assembly Code", "Object Code"], 0)
    create_question(cd_quiz, "YACC stands for:", ["Yet Another Compiler-Compiler", "Yielding Another Compiler", "Yellow Alpha Compiler", "Young Advanced Compiler"], 0)
    create_question(cd_quiz, "Dead code elimination is a part of:", ["Code Optimization", "Lexical Analysis", "Syntax Analysis", "Loading"], 0)
    create_question(cd_quiz, "Which graph is used for data flow analysis?", ["Control Flow Graph", "DAG", "AST", "Binary Tree"], 0)
    create_question(cd_quiz, "The process of assigning physical addresses to variables is:", ["Memory Allocation", "Scanning", "Parsing", "Tokenizing"], 0)
    create_question(cd_quiz, "Three-address code is an example of:", ["Intermediate Code", "Target Code", "Source Code", "Semantic Code"], 0)
    create_question(cd_quiz, "What is a semantic error?", ["Type mismatch", "Missing semicolon", "Invalid token", "Divide by zero"], 0)
    create_question(cd_quiz, "Parser generates what structure?", ["Parse Tree", "Symbol Table", "Token Stream", "Linked List"], 0)
    create_question(cd_quiz, "Which phase comes after Code Optimization?", ["Code Generation", "Syntax Analysis", "Lexical Analysis", "Semantic Analysis"], 0)

    # --- OS ---
    os_quiz = get_quiz("Operating Systems", "Threads, Scheduling, and Memory Management.", os_cat)
    create_question(os_quiz, "What is a deadlock?", ["A state where processes wait for each other", "A fast process", "A crashed OS", "A deleted file"], 0)
    create_question(os_quiz, "Which scheduling algorithm is non-preemptive?", ["First-Come First-Served", "Round Robin", "Shortest Remaining Time", "Priority Scheduling"], 0)
    create_question(os_quiz, "What is virtual memory?", ["Storage technique that uses disk space as RAM", "Actual RAM", "GPU Memory", "Cloud Storage"], 0)
    create_question(os_quiz, "The main purpose of an OS is to:", ["Manage hardware and software resources", "Create websites", "Edit photos", "Compile code"], 0)
    create_question(os_quiz, "Which system call is used to create a new process in Unix?", ["fork()", "exec()", "wait()", "exit()"], 0)
    create_question(os_quiz, "What is thrashing?", ["High paging activity leading to low CPU util", "Formatting a disk", "Deleting files", "Fast CPU"], 0)
    create_question(os_quiz, "Semaphore is used for:", ["Process synchronization", "File compression", "Memory allocation", "Network routing"], 0)
    create_question(os_quiz, "What is a kernel?", ["The core part of the Operating System", "A user application", "A web browser", "A shell script"], 0)
    create_question(os_quiz, "Banker's Algorithm is used for:", ["Deadlock Avoidance", "Deadlock Detection", "Memory Management", "Disk Scheduling"], 0)
    create_question(os_quiz, "What is a process?", ["A program in execution", "A file on disk", "A line of code", "A user input"], 0)
    create_question(os_quiz, "Fragmentation occurs in:", ["Memory Management", "Disk I/O", "CPU Scheduling", "Cache"], 0)
    create_question(os_quiz, "LRU stands for:", ["Least Recently Used", "Last Read Unit", "Low Rate User", "Long Run Union"], 0)
    create_question(os_quiz, "What is a shell?", ["User interface for OS services", "The hard disk case", "A protected file", "Internal memory"], 0)
    create_question(os_quiz, "Which OS is open source?", ["Linux", "Windows", "MacOS", "iOS"], 0)
    create_question(os_quiz, "What is context switching?", ["Switching CPU from one process to another", "Changing monitors", "Switching folders", "Rebooting"], 0)

    # --- DBMS ---
    dbms_quiz = get_quiz("Database Management", "SQL, Normalization, and Transactions.", dbms_cat)
    create_question(dbms_quiz, "What does SQL stand for?", ["Structured Query Language", "Standard Quota Logic", "Sequential Query List", "Simple Query Language"], 0)
    create_question(dbms_quiz, "Which normal form deals with partial functional dependency?", ["2NF", "1NF", "3NF", "BCNF"], 0)
    create_question(dbms_quiz, "What is a primary key?", ["Unique identifier for a record", "A common field", "A foreign link", "A secondary index"], 0)
    create_question(dbms_quiz, "ACID properties ensure:", ["Transaction reliability", "Database speed", "Data encryption", "User login"], 0)
    create_question(dbms_quiz, "Which command is used to remove a table?", ["DROP", "DELETE", "REMOVE", "TRUNCATE"], 0)
    create_question(dbms_quiz, "What is a foreign key?", ["A key used to link two tables", "A key from another DB", "A secret key", "The main key"], 0)
    create_question(dbms_quiz, "Which operation combines rows from two tables?", ["JOIN", "UNION", "GROUP BY", "SELECT"], 0)
    create_question(dbms_quiz, "What is data redundancy?", ["Duplication of data", "Loss of data", "Data speed", "Data security"], 0)
    create_question(dbms_quiz, "What does 'Atomicity' mean in ACID?", ["Entire transaction succeeds or fails", "Data is consistent", "Transaction is isolated", "Data is permanent"], 0)
    create_question(dbms_quiz, "Standard for communication between databases is:", ["ODBC", "HTTP", "FTP", "SMTP"], 0)
    create_question(dbms_quiz, "Which command is DDL?", ["CREATE", "INSERT", "UPDATE", "DELETE"], 0)
    create_question(dbms_quiz, "What is a view in SQL?", ["A virtual table", "A real table", "A query results", "A database schema"], 0)
    create_question(dbms_quiz, "NoSQL databases are:", ["Non-relational", "Only for numbers", "Slow", "Deprecated"], 0)
    create_question(dbms_quiz, "Index is used for:", ["Faster data retrieval", "Data security", "Smaller size", "Formatting"], 0)
    create_question(dbms_quiz, "Normalization is used to:", ["Minimize redundancy", "Maximize speed", "Format data", "Upload data"], 0)

    # --- C ---
    c_quiz = get_quiz("C Programming", "Pointers, Memory, and Syntax.", c_cat)
    create_question(c_quiz, "Who developed C?", ["Dennis Ritchie", "Ken Thompson", "Bjarne Stroustrup", "James Gosling"], 0)
    create_question(c_quiz, "What is the size of an int in C (typically)?", ["4 bytes", "1 byte", "2 bytes", "8 bytes"], 0)
    create_question(c_quiz, "Which operator is used for pointers?", ["*", "&", "#", "@"], 0)
    create_question(c_quiz, "Which function is used for dynamic memory allocation?", ["malloc()", "alloc()", "new()", "create()"], 0)
    create_question(c_quiz, "What indicates the end of a string in C?", ["\\0", "\\n", ";", "."], 0)
    create_question(c_quiz, "What is the result of 5 % 2?", ["1", "2.5", "0", "2"], 0)
    create_question(c_quiz, "Which keyword is used to return a value from a function?", ["return", "yield", "send", "exit"], 0)
    create_question(c_quiz, "How do you declare a constant in C?", ["const", "final", "static", "None"], 0)
    create_question(c_quiz, "Which header file is needed for printf()?", ["stdio.h", "conio.h", "stdlib.h", "math.h"], 0)
    create_question(c_quiz, "C is a:", ["Procedural Language", "Object Oriented Language", "Scripting Language", "Strictly Functional"], 0)
    create_question(c_quiz, "Which of these is not a valid identifier?", ["2name", "_name", "name2", "Name"], 0)
    create_question(c_quiz, "What does 'break' do in a loop?", ["Exits the loop", "Starts new iteration", "Pauses loop", "Nothing"], 0)
    create_question(c_quiz, "Recursive function is a function that:", ["Calls itself", "Calls main()", "Never ends", "Is empty"], 0)
    create_question(c_quiz, "What is a structure in C?", ["User defined data type", "A loop", "A function", "A pointer"], 0)
    create_question(c_quiz, "Arrays in C start at index:", ["0", "1", "-1", "Any"], 0)

    # --- C++ ---
    cpp_quiz = get_quiz("C++ Mastery", "OOP, Templates, and STL.", cpp_cat)
    create_question(cpp_quiz, "Who created C++?", ["Bjarne Stroustrup", "Dennis Ritchie", "James Gosling", "Bjarne Stroustrup"], 0)
    create_question(cpp_quiz, "What is encapsulation?", ["Wrapping data and functions into a single unit", "Hiding code", "Fast execution", "Inheritence"], 0)
    create_question(cpp_quiz, "Which keyword is used for inheritance in C++?", ["public", "extends", "implements", ":"], 3)
    create_question(cpp_quiz, "What is a constructor?", ["A function called when object is created", "A tool to build code", "A memory manager", "A special pointer"], 0)
    create_question(cpp_quiz, "Polymorphism means:", ["One interface, multiple forms", "Many objects", "Data hiding", "Code reuse"], 0)
    create_question(cpp_quiz, "Which operator is used for output in C++?", ["<<", ">>", "<", ">"], 0)
    create_question(cpp_quiz, "Standard library for I/O in C++ is?", ["iostream", "stdio.h", "conio.h", "fstream"], 0)
    create_question(cpp_quiz, "What is 'this' pointer?", ["Points to the current object", "Points to previous object", "A global pointer", "NULL pointer"], 0)
    create_question(cpp_quiz, "Virtual functions are used for:", ["Runtime Polymorphism", "Compile-time Polymorphism", "Fast loops", "Hiding private data"], 0)
    create_question(cpp_quiz, "STL stands for:", ["Standard Template Library", "Static Type Logic", "Simple Tool Library", "Structured Template List"], 0)
    create_question(cpp_quiz, "Reference variable uses which symbol?", ["&", "*", "#", "@"], 0)
    create_question(cpp_quiz, "What is a friend function?", ["A function with access to private members", "A public function", "The main function", "An inherited function"], 0)
    create_question(cpp_quiz, "Destructor name starts with:", ["~", "!", "#", "@"], 0)
    create_question(cpp_quiz, "Which keyword handles exceptions?", ["try/catch", "throw/catch", "error/handle", "if/else"], 0)
    create_question(cpp_quiz, "Default access specifier for class members is:", ["private", "public", "protected", "none"], 0)

    # --- Java ---
    java_quiz = get_quiz("Java Core", "JVM, OOP, and Multithreading.", java_cat)
    create_question(java_quiz, "Java is platform independent because of:", ["Bytecode and JVM", "Compilers", "Windows", "Silicon chips"], 0)
    create_question(java_quiz, "Which keyword is used to inherit a class?", ["extends", "implements", "inherits", "import"], 0)
    create_question(java_quiz, "What is the root class of all Java classes?", ["Object", "Main", "Class", "Root"], 0)
    create_question(java_quiz, "Which component is responsible for running Java bytecode?", ["JVM", "JRE", "JDK", "JIT"], 0)
    create_question(java_quiz, "What is Garbage Collection?", ["Automated memory management", "Deleting files", "Clearing cache", "Input validation"], 0)
    create_question(java_quiz, "Which keyword creates a constant?", ["final", "static", "const", "finalized"], 0)
    create_question(java_quiz, "How many primitive data types in Java?", ["8", "10", "5", "12"], 0)
    create_question(java_quiz, "Main method in Java is always:", ["public static void main", "private void main", "static void main", "public void main"], 0)
    create_question(java_quiz, "Which package is imported by default?", ["java.lang", "java.util", "java.io", "java.net"], 0)
    create_question(java_quiz, "What is an Interface?", ["A blueprint of a class with abstract methods", "A user UI", "A network tool", "A database link"], 0)
    create_question(java_quiz, "Which keyword refers to the parent class?", ["super", "this", "parent", "base"], 0)
    create_question(java_quiz, "What is a Thread?", ["Lightweight subprocess", "A string", "A memory block", "A file link"], 0)
    create_question(java_quiz, "Is Java purely Object Oriented?", ["No (primitives exist)", "Yes", "Only for web", "None"], 0)
    create_question(java_quiz, "What is JIT?", ["Just-in-Time Compiler", "Java Integration Tool", "Joined Information Type", "None"], 0)
    create_question(java_quiz, "Exception handling uses:", ["try-catch", "if-else", "switch", "for"], 0)

    # --- HTML ---
    html_quiz = get_quiz("HTML Essentials", "Structure the web.", html_cat)
    create_question(html_quiz, "What does HTML stand for?", ["HyperText Markup Language", "Home Tool Markup Language", "Hyperlink Text Mark Language", "Hyper Transfer Main Language"], 0)
    create_question(html_quiz, "Which tag is used for the largest heading?", ["<h1>", "<h6>", "<head>", "<big>"], 0)
    create_question(html_quiz, "What is the correct tag for a line break?", ["<br>", "<lb>", "<break>", "<hr>"], 0)
    create_question(html_quiz, "Which attribute is used to provide an image source?", ["src", "href", "link", "url"], 0)
    create_question(html_quiz, "What is the correct tag for a hyperlink?", ["<a>", "<link>", "<url>", "<li>"], 0)
    create_question(html_quiz, "Which tag is used for an unordered list?", ["<ul>", "<ol>", "<li>", "<dl>"], 0)
    create_question(html_quiz, "How do you make a checkbox?", ['<input type="checkbox">', "<checkbox>", "<check>", '<input type="check">'], 0)
    create_question(html_quiz, "Which tag defines important text?", ["<strong>", "<bold>", "<imp>", "<hi>"], 0)
    create_question(html_quiz, "What is the correct tag for a table?", ["<table>", "<td>", "<tr>", "<tab>"], 0)
    create_question(html_quiz, "Comments in HTML start with:", ["<!--", "//", "/*", "#"], 0)
    create_question(html_quiz, "Which tag defines the document title?", ["<title>", "<head>", "<meta>", "<header>"], 0)
    create_question(html_quiz, "Which tag contains all page content?", ["<body>", "<html>", "<main>", "<divbody>"], 0)
    create_question(html_quiz, "Correct tag for <iframe>?", ["<iframe>", "<frame>", "<sub>", "<window>"], 0)
    create_question(html_quiz, "Tag used for dropdown lists?", ["<select>", "<list>", "<dropdown>", "<input>"], 0)
    create_question(html_quiz, "Which HTML5 tag is for playing videos?", ["<video>", "<movie>", "<play>", "<media>"], 0)

    # --- CSS ---
    css_quiz = get_quiz("CSS Styling", "Design and Layout.", css_cat)
    create_question(css_quiz, "What does CSS stand for?", ["Cascading Style Sheets", "Creative Style Sheets", "Computer Style Sheets", "Colorful Style Sheets"], 0)
    create_question(css_quiz, "Where is the correct place to link an external stylesheet?", ["Inside <head>", "Inside <body>", "At the bottom", "In <footer>"], 0)
    create_question(css_quiz, "Which property is used to change background color?", ["background-color", "color", "bgcolor", "fill"], 0)
    create_question(css_quiz, "How do you add color to text?", ["color: red;", "text-color: red;", "font-color: red;", "fg: red;"], 0)
    create_question(css_quiz, "Which property controls text size?", ["font-size", "text-size", "big", "font-style"], 0)
    create_question(css_quiz, "How do you make text bold?", ["font-weight: bold;", "style: bold;", "font: bold;", "text-bold: true;"], 0)
    create_question(css_quiz, "Which property is used to center text?", ["text-align: center;", "align: center;", "margin: center;", "horizontal-align: center;"], 0)
    create_question(css_quiz, "Box model includes margin, border, padding, and:", ["Content", "Spacing", "Color", "Size"], 0)
    create_question(css_quiz, "Which selector targets an element with ID 'header'?", ["#header", ".header", "header", "*header"], 0)
    create_question(css_quiz, "Which property sets space between elements?", ["margin", "padding", "border", "gap"], 0)
    create_question(css_quiz, "Which property sets internal space?", ["padding", "margin", "spacing", "border"], 0)
    create_question(css_quiz, "What is the default position value?", ["static", "relative", "absolute", "fixed"], 0)
    create_question(css_quiz, "Which property hides an element?", ["display: none;", "visibility: hidden;", "Both", "None"], 2)
    create_question(css_quiz, "Z-index works only on:", ["Positioned elements", "All elements", "Only divs", "Images"], 0)
    create_question(css_quiz, "How do you select elements with class 'test'?", [".test", "#test", "test", "*test"], 0)

    # --- JavaScript ---
    js_quiz = get_quiz("JavaScript Basics", "Programming the browser.", js_cat)
    create_question(js_quiz, "Which keyword declares a variable?", ["var", "string", "declare", "dim"], 0)
    create_question(js_quiz, "How do you write 'Hello' in an alert box?", ["alert('Hello');", "msg('Hello');", "console.log('Hello');", "print('Hello');"], 0)
    create_question(js_quiz, "What is the correct syntax for a function?", ["function myFunc()", "func myFunc()", "def myFunc()", "sub myFunc()"], 0)
    create_question(js_quiz, "How do you call a function 'myFunc'?", ["myFunc()", "call myFunc()", "invoke myFunc()", "exec myFunc()"], 0)
    create_question(js_quiz, "Which operator is for strict equality?", ["===", "==", "=", "!="], 0)
    create_question(js_quiz, "How to add a comment in JS?", ["//", "<!--", "#", "**"], 0)
    create_question(js_quiz, "What is an array in JS?", ["['a', 'b']", "{'a', 'b'}", "(a, b)", "<a, b>"], 0)
    create_question(js_quiz, "Result of 2 + '2'?", ["'22'", "4", "Error", "NaN"], 0)
    create_question(js_quiz, "Which event happens on a click?", ["onclick", "onpress", "onhover", "onchange"], 0)
    create_question(js_quiz, "How to find the length of a string?", ["str.length", "str.len", "size(str)", "length(str)"], 0)
    create_question(js_quiz, "DOM stands for?", ["Document Object Model", "Data Object Main", "Digital Online Meta", "Default Object Mode"], 0)
    create_question(js_quiz, "Which keyword is for constant variables?", ["const", "let", "var", "final"], 0)
    create_question(js_quiz, "Arrow function syntax?", ["() => {}", "func => {}", "=> ()", "-> {}"], 0)
    create_question(js_quiz, "Which method parses a JSON string?", ["JSON.parse()", "JSON.stringify()", "parse()", "convert()"], 0)
    create_question(js_quiz, "Which method waits for a promise?", ["await", "wait", "hold", "pause"], 0)

    # --- Software Design ---
    design_quiz = get_quiz("Software Design", "Patterns and principles.", design_cat)
    create_question(design_quiz, "What is SOLID?", ["Design principles for OOP", "A hard code", "A file format", "A testing tool"], 0)
    create_question(design_quiz, "What does the 'S' in SOLID stand for?", ["Single Responsibility", "Static", "Shared", "System"], 0)
    create_question(design_quiz, "Which pattern ensures only one instance?", ["Singleton", "Factory", "Observer", "Strategy"], 0)
    create_question(design_quiz, "DRY principle stands for:", ["Don't Repeat Yourself", "Do Repeat Your-work", "Data Read Yearly", "Default Run Young"], 0)
    create_question(design_quiz, "MVC stands for:", ["Model View Controller", "Main Value Center", "Meta Visual Core", "Module Version Check"], 0)
    create_question(design_quiz, "The Observer pattern is used for:", ["Subscribing to events", "Creating objects", "Managing memory", "Hiding data"], 0)
    create_question(design_quiz, "Refactoring means:", ["Improving code structure without changing behavior", "Rewriting from scratch", "Adding new features", "Deleting code"], 0)
    create_question(design_quiz, "UML stands for:", ["Unified Modeling Language", "Universal Mood Link", "User Main List", "Unique Module Language"], 0)
    create_question(design_quiz, "What is Loose Coupling?", ["Reducing dependencies between modules", "Removing all code", "Fast coding", "Using global variables"], 0)
    create_question(design_quiz, "What is a Design Pattern?", ["Reusable solution to a common problem", "A UI template", "A color scheme", "A testing framework"], 0)
    create_question(design_quiz, "Agile is a:", ["Development methodology", "Programming language", "Database name", "Cloud platform"], 0)
    create_question(design_quiz, "Unit Testing tests:", ["Individual components", "The whole system", "The user UI", "The database speed"], 0)
    create_question(design_quiz, "What is a User Story?", ["Short description of a feature from user view", "A long manual", "A code comment", "A bug report"], 0)
    create_question(design_quiz, "KISS principle:", ["Keep It Simple, Stupid", "King Is Super Strong", "Key Is Simple Space", "Knowledge Is Super Smart"], 0)
    create_question(design_quiz, "What is Technical Debt?", ["Cost of future rework caused by easy solutions", "Bank loan", "Server cost", "Employee salary"], 0)

    # --- Cloud Computing ---
    cloud_quiz = get_quiz("Cloud Computing", "AWS, Azure, and Services.", cloud_cat)
    create_question(cloud_quiz, "What does SaaS stand for?", ["Software as a Service", "System as a Service", "Standard as a Service", "Storage as a Service"], 0)
    create_question(cloud_quiz, "AWS is owned by:", ["Amazon", "Google", "Microsoft", "Meta"], 0)
    create_question(cloud_quiz, "Azure is the cloud platform for:", ["Microsoft", "Oracle", "IBM", "Adobe"], 0)
    create_question(cloud_quiz, "Google's cloud service name?", ["GCP", "AWS", "Azure", "Cloud 1"], 0)
    create_question(cloud_quiz, "What is Serverless computing?", ["Provider manages the server infrastructure", "No servers used", "Local computer", "Physical hardware"], 0)
    create_question(cloud_quiz, "What is an S3 bucket in AWS?", ["Storing objects/files", "Running code", "Managing DBs", "User login"], 0)
    create_question(cloud_quiz, "Scalability in cloud means:", ["Ability to handle increasing load", "Changing code", "Deleting users", "Moving servers"], 0)
    create_question(cloud_quiz, "What is the Cloud?", ["Servers accessed over the internet", "A literal cloud", "A local drive", "A floppy disk"], 0)
    create_question(cloud_quiz, "PaaS means:", ["Platform as a Service", "Product as a Service", "Performance as a Service", "Program as a Service"], 0)
    create_question(cloud_quiz, "IaaS means:", ["Infrastructure as a Service", "Internet as a Service", "Instruction as a Service", "Information as a Service"], 0)
    create_question(cloud_quiz, "What is a Public Cloud?", ["Services offered over the public internet", "A free cloud", "Open source cloud", "Local cloud"], 0)
    create_question(cloud_quiz, "Docker is used for:", ["Containerization", "Word processing", "Web browsing", "Database design"], 0)
    create_question(cloud_quiz, "Kubernetes is for:", ["Container orchestration", "Editing photos", "Sending emails", "Compiling Java"], 0)
    create_question(cloud_quiz, "Main benefit of Cloud is:", ["Cost efficiency and flexibility", "Colors", "Heavy hardware", "Privacy"], 0)
    create_question(cloud_quiz, "Latency in cloud refers to:", ["Delay in data transmission", "Data size", "Cost", "Security"], 0)

    print("Seeding complete!")

if __name__ == "__main__":
    seed_data()
