# Generated by Django 5.2.4 on 2026-03-10 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_badge_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='min_score',
            field=models.IntegerField(default=100, help_text='Minimum score percentage to earn this badge'),
        ),
        migrations.AddField(
            model_name='badge',
            name='tier',
            field=models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold')], default='GOLD', max_length=10),
        ),
        migrations.AlterField(
            model_name='badge',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='quiz.category'),
        ),
    ]
